### PR TITLE
fix: add elastic-agent as available service

### LINKED ISSUE #492: Failed to start elastic-agent when services flag is passed
Hi folks! :wave: I’m having an issue with the elastic-package tool, while starting the agent in the stack command: 

```
$ elastic-package stack up --daemon --version 8.0.0-56a61c29-SNAPSHOT --services elasticsearch,fleet-server,kibana,package-registry,elastic-agent -v
2021/08/23 11:17:24 DEBUG Enable verbose logging
2021/08/23 11:17:24 DEBUG Distribution built without a version tag, can't determine release chronology. Please consider using official releases at https://github.com/elastic/elastic-package/releases
Boot up the Elastic stack
Error: validating services failed: service "elastic-agent" is not available
```

It seems the `elastic-agent`, although being participant of the snapshot.yml descriptor, is not enabled as an `availableServices` in stack.go file.

If you agree, I'm going to send a fix for that.

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It adds the elastic-agent service as available service in the stack

## Why is it important?
It's not possible to start the stack without the agent, and then start the agent alone, even though the elastic-agent is part of the initial compose snapshot.yml file. The use case where I discovered this bug is:

1. run the stack without the agent
2. wait for the stack is ready (kibana, es, fleet-server)
3. run the agent to automatically enroll

## Steps to reproduce
1. elastic-package stack up --daemon --version 8.0.0-56a61c29-SNAPSHOT --services elasticsearch,fleet-server,kibana,package-registry -v
1. elastic-package stack up --daemon --version 8.0.0-56a61c29-SNAPSHOT --services elastic-agent

#### Expected behaviour
The agent is started alongside the existing stack

#### Current behaviour
The program fails as the agent is not part of the available services in the stack
```shell
$ elastic-package stack up --daemon --version 8.0.0-SNAPSHOT --services elasticsearch,fleet-server,kibana,package-registry,elastic-agent -v
2021/08/23 11:17:37 DEBUG Enable verbose logging
2021/08/23 11:17:37 DEBUG Distribution built without a version tag, can't determine release chronology. Please consider using official releases at https://github.com/elastic/elastic-package/releases
Boot up the Elastic stack
Error: validating services failed: service "elastic-agent" is not available
```

## Related issues
- Closes #492

### CODE REVIEW

File: cmd/stack_test.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+	"fmt"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestValidateServicesFlag(t *testing.T) {
+	t.Run("a non available service returns error", func(t *testing.T) {
+		err := validateServicesFlag([]string{"non-existing-service"})
+		require.NotNil(t, err)
```
Comment (jsoriano) [inline cmd/stack_test.go:17]: Nit. Use `require.Error` instead of `require.NotNil`?

**Review by jsoriano — APPROVED** [review]

File: cmd/stack_test.go (hunk 1 above)
Comment (mdelapenya) [reply cmd/stack_test.go]: Done in https://github.com/elastic/elastic-package/pull/493/commits/18efbc9039fe57d4703260a02b91432121cdbd89

**Review by jsoriano — APPROVED** [review]

**Comment by mdelapenya** [comment]
It'd be great if we are able to release a patch/minor version including this fix. What is the regular procedure for that?

**Review by v1v — APPROVED** [review]

**Review by jsoriano — APPROVED** [review]

File: cmd/stack.go [hunk 2]
```diff
@@ -19,6 +19,7 @@ import (
 )
 
 var availableServices = map[string]struct{}{
+	"elastic-agent":    {},
```
Comment (mtojek) [inline cmd/stack.go:22]: Few words of explanation - `elastic-agent` depends on everything so:

`--services elasticsearch,fleet-server,kibana,package-registry,elastic-agent` is equal to "no --services" at all or `--services elastic-agent`. This argument value was skipped as it might be a bit confusing. Consider `--services elasticsearch,elastic-agent`, it will start all services from the stack even though only two are selected.

Anyway, I'm good with this PR. I just wanted to explain the story behind it.

**Review by mtojek — APPROVED** [review]

File: cmd/stack.go (hunk 2 above)
Comment (mdelapenya) [reply cmd/stack.go:22]: Thanks for the explanation @mtojek. The use case I expose here comes from https://github.com/elastic/e2e-testing/pull/1502, where we plan to integrate elastic-package as the de-facto deployment tool for our e2e testing framework. It's still a PoC, but it fairly works :)

Comment (mtojek) [reply cmd/stack.go:22]: Actually you might be interested also in this topic: https://github.com/elastic/elastic-package/issues/479

**Comment by mtojek** [comment]
@mdelapenya I guess this is ready to be merged.
