### PR TITLE
Fix retrieve logs in elastic-package stack dump

### LINKED ISSUE #1251: Container logs are not written in elastic-package stack dump using docker-compose v2
Relates #1116
Blocks #1188

Logs cannot be retrieved when docker-compose v2 is used in the system.

Using docker-compose v1:

```shell
 $ docker-compose version --short
1.25.5

 $ elastic-package stack up -v -d --version 8.7.0
 ...

 $ elastic-package stack dump
2023/05/05 13:31:25 ERROR can't copy internal logs (service: elastic-agent): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack_elastic-agent_1\n"): exit status 1
2023/05/05 13:31:27 ERROR can't copy internal logs (service: fleet-server): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack_fleet-server_1\n"): exit status 1
Path to stack dump: elastic-stack-dump
Done

 $ ls -l elastic-stack-dump/logs
total 816
-rw-r--r-- 1 mariorodriguez mariorodriguez 147046 may  5 13:31 elastic-agent.log
-rw-r--r-- 1 mariorodriguez mariorodriguez 325907 may  5 13:31 elasticsearch.log
-rw-r--r-- 1 mariorodriguez mariorodriguez 286197 may  5 13:31 fleet-server.log
-rw-r--r-- 1 mariorodriguez mariorodriguez  15648 may  5 13:31 kibana.log
-rw-r--r-- 1 mariorodriguez mariorodriguez  54461 may  5 13:31 package-registry.log

 $ elastic-package stack down
```

Usign docker-compose v2:
```shell
 $ docker-compose version --short
2.17.2

 $ elastic-package stack up -v -d --version 8.7.0

 $ elastic-package stack dump
2023/05/05 13:38:39 ERROR can't fetch service logs (service: elasticsearch): running command failed: exit status 15
2023/05/05 13:38:39 ERROR can't fetch service logs (service: elastic-agent): running command failed: exit status 15
2023/05/05 13:38:39 ERROR can't copy internal logs (service: elastic-agent): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack-elastic-agent-1\n"): exit status 1
2023/05/05 13:38:39 ERROR can't fetch service logs (service: fleet-server): running command failed: exit status 15
2023/05/05 13:38:39 ERROR can't copy internal logs (service: fleet-server): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack-fleet-server-1\n"): exit status 1
2023/05/05 13:38:39 ERROR can't fetch service logs (service: kibana): running command failed: exit status 15
2023/05/05 13:38:39 ERROR can't fetch service logs (service: package-registry): running command failed: exit status 15
Path to stack dump: elastic-stack-dump
Done

 $ ls -l elastic-stack-dump/logs
total 0

 $ elastic-package stack down
```

For both versions, there is a common error related to some internal logs from fleet-server and elastic-agent:
- Path used by elastic-package does not exist in the container: /usr/share/elastic-agent/state/data/logs/default
- Logs are written to: /usr/share/elastic-agent/state/data/logs/elastic-agent-*.ndjson

### PR DESCRIPTION
**Pull request by mrodm**
Closes #1251 

This PR solves two issues related to logs retrieved by `elastic-package stack dump` command:
- using docker-compose v2 some environment variables are missing
- starting with 8.6.0, paths where logs can be found for elastic-agent and fleet-server has changed to be one unified log file:
    - Prior to that version those internal logs follow this pattern:
        - `/usr/share/elastic-agent/state/data/logs/default/*` (elastic-package copy these ones)
        - `/usr/share/elastic-agent/state/data/logs/*`
    - Since 8.6.0, there is no `default` folder
        - `/usr/share/elastic-agent/state/data/logs/`

Example of current failures against 8.8.0-SNAPSHOT:
- using docker-compose v1:
    - some files cannot be copied due to the missing `default` folder
```
 $ docker-compose version --short
1.25.5

 $ elastic-package stack up -v -d --version 8.8.0-SNAPSHOT
 $ elastic-package stack dump
2023/05/05 17:49:25 ERROR can't copy internal logs (service: elastic-agent): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack_elastic-agent_1\n"): exit status 1
2023/05/05 17:49:27 ERROR can't copy internal logs (service: fleet-server): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack_fleet-server_1\n"): exit status 1
Path to stack dump: elastic-stack-dump
Done

 $ tree elastic-stack-dump/logs
elastic-stack-dump/logs
├── elastic-agent.log
├── elasticsearch.log
├── fleet-server.log
├── kibana.log
└── package-registry.log

0 directories, 5 files
``` 
- using docker-compose v2
```
 $ docker-compose version --short
2.17.2

 $ elastic-package stack up -v -d --version 8.8.0-SNAPSHOT
 $ elastic-package stack dump
2023/05/05 17:51:57 ERROR can't fetch service logs (service: elasticsearch): running command failed: exit status 15
2023/05/05 17:51:57 ERROR can't fetch service logs (service: elastic-agent): running command failed: exit status 15
2023/05/05 17:51:57 ERROR can't copy internal logs (service: elastic-agent): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack-elastic-agent-1\n"): exit status 1
2023/05/05 17:51:57 ERROR can't fetch service logs (service: fleet-server): running command failed: exit status 15
2023/05/05 17:51:57 ERROR can't copy internal logs (service: fleet-server): docker copy failed: could not copy files from the container (stderr="Error response from daemon: Could not find the file /usr/share/elastic-agent/state/data/logs/default in container elastic-package-stack-fleet-server-1\n"): exit status 1
2023/05/05 17:51:57 ERROR can't fetch service logs (service: kibana): running command failed: exit status 15
2023/05/05 17:51:57 ERROR can't fetch service logs (service: package-registry): running command failed: exit status 15
Path to stack dump: elastic-stack-dump
Done

 $ tree elastic-stack-dump/logs
elastic-stack-dump/logs/

0 directories, 0 files

 $ elastic-package stack down
```

Example of files present in different Elastic stack versions for elastic-agent-internal:
- 7.17.10
```
 $ tree -l elastic-stack-dump-7.17.10/logs/elastic-agent-internal/
elastic-stack-dump-7.17.10/logs/elastic-agent-internal/
├── default
│   ├── filebeat-json.log
│   ├── filebeat-json.log-2023-05-05-15-1
│   ├── metricbeat-json.log
│   └── metricbeat-json.log-2023-05-05-15-1
└── elastic-agent-json.log-20230505150712

1 directory, 5 files
```
- 8.0.0
```
 $ tree elastic-stack-dump-8.0.0/logs/elastic-agent-internal/
elastic-stack-dump-8.0.0/logs/elastic-agent-internal/
├── default
│   ├── filebeat-20230505-1.ndjson
│   ├── filebeat-20230505-2.ndjson
│   ├── filebeat-20230505-3.ndjson
│   ├── filebeat-20230505.ndjson
│   ├── metricbeat-20230505-1.ndjson
│   ├── metricbeat-20230505-2.ndjson
│   ├── metricbeat-20230505-3.ndjson
│   ├── metricbeat-20230505-4.ndjson
│   ├── metricbeat-20230505-5.ndjson
│   └── metricbeat-20230505.ndjson
└── elastic-agent-20230505.ndjson

1 directory, 11 files
```
- 8.5.0
```
 $ tree elastic-stack-dump-8.5.0/logs/elastic-agent-internal/
elastic-stack-dump-8.5.0/logs/elastic-agent-internal/
├── default
│   ├── filebeat-20230505-1.ndjson
│   ├── filebeat-20230505-2.ndjson
│   ├── filebeat-20230505-3.ndjson
│   ├── filebeat-20230505.ndjson
│   ├── metricbeat-20230505-1.ndjson
│   └── metricbeat-20230505.ndjson
└── elastic-agent-20230505.ndjson

1 directory, 7 files
```
- 8.8.0-SNAPSHOT
```
 $ tree elastic-stack-dump-8.8.0-SNAPSHOT/logs/elastic-agent-internal/
elastic-stack-dump-8.8.0-SNAPSHOT/logs/elastic-agent-internal/
└── elastic-agent-20230505.ndjson

0 directories, 1 file
```

## Checklist
- [x] Tested using docker-compose v1
- [x] Tested using docker-compose v2
- [x] Tested with different Elastic stack versions (7.17.10, 8.0.0, 8.5.0, 8.6.0 and 8.8.0-SNAPSHOT)

## How to test this change

- Check docker-compose version installed in your system:
```
 $ docker-compose version --short
2.17.2
```
- Start a Elastic stack using elastic-package with the desired version (e.g. 8.8.0-SNAPSHOT)
```
 $ elastic-package stack up -v -d --version 8.8.0-SNAPSHOT
```
- Dump information from the stack command and check logs
```
 $ elastic-package stack dump
Path to stack dump: elastic-stack-dump
Done
 $ tree elastic-stack-dump/logs/
elastic-stack-dump/logs/
├── elastic-agent-internal
│   └── elastic-agent-20230505.ndjson
├── elastic-agent.log
├── elasticsearch.log
├── fleet-server-internal
│   ├── elastic-agent-20230505-1.ndjson
│   └── elastic-agent-20230505.ndjson
├── fleet-server.log
├── kibana.log
└── package-registry.log
```

### CODE REVIEW

File: internal/stack/logs.go [hunk 1]
```diff
@@ -15,13 +15,19 @@ import (
...
+	}
+
 	p, err := compose.NewProject(DockerComposeProjectName, snapshotFile)
 	if err != nil {
 		return nil, errors.Wrap(err, "could not create docker compose project")
 	}
 
 	opts := compose.CommandOptions{
 		Env: newEnvBuilder().
+			withEnvs(appConfig.StackImageRefs(install.DefaultStackVersion).AsEnv()).
```
Comment (mrodm) [inline internal/stack/logs.go:30]: There are still these warnings:
```
WARN[0000] The "PROFILE_NAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PROFILE_NAME" variable is not set. Defaulting to a blank string.
```

but that missing environment variable does not make fail the command as these ones:
```
WARN[0000] The "ELASTIC_AGENT_IMAGE_REF" variable is not set. Defaulting to a blank string. 
WARN[0000] The "KIBANA_IMAGE_REF" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ELASTIC_AGENT_IMAGE_REF" variable is not set. Defaulting to a blank string.
WARN[0000] The "ELASTICSEARCH_IMAGE_REF" variable is not set. Defaulting to a blank string.
```
As an eaxmple of error:
> service "elasticsearch" has neither an image nor a build context specified: invalid compose project

Comment (mrodm) [reply internal/stack/logs.go:31]: Added that missing env. variable in https://github.com/elastic/elastic-package/pull/1252/commits/a7c35c788f9a7b30a05a2ca65aaecc242095a9eb

**Review by kpollich — APPROVED** [review]
LGTM - thanks for the fix.

File: internal/stack/logs.go [hunk 2]
```diff
@@ -12,18 +12,30 @@ import (
...
 		return nil, errors.Wrap(err, "could not create docker compose project")
 	}
 
+	envBuilder := newEnvBuilder().
+		withEnvs(appConfig.StackImageRefs(install.DefaultStackVersion).AsEnv()).
+		withEnv(stackVariantAsEnv(install.DefaultStackVersion))
+
+	if profile != nil {
+		envBuilder = envBuilder.withEnvs(profile.ComposeEnvVars())
+	}
```
Comment (mrodm) [inline internal/stack/logs.go:35]: Does it make sense to add this safeguard for the profile?

File: internal/stack/logs.go [hunk 3]
```diff
@@ -12,17 +12,27 @@ import (
 	"github.com/elastic/elastic-package/internal/compose"
 	"github.com/elastic/elastic-package/internal/docker"
 	"github.com/elastic/elastic-package/internal/install"
+	"github.com/elastic/elastic-package/internal/profile"
 )
 
-func dockerComposeLogs(serviceName string, snapshotFile string) ([]byte, error) {
+func dockerComposeLogs(serviceName string, profile *profile.Profile) ([]byte, error) {
```
Comment (mrodm) [inline internal/stack/logs.go:18]: Use `profile` as parameter instead of using `snapshotFile` as parameter.
Having the profile as parameter, allows us:
- obtain the snapshot file path
- get the needed Environment variables from the Profile for the `docker-compose logs` command

File: internal/stack/logs.go [hunk 4]
```diff
@@ -48,7 +58,7 @@ func copyDockerInternalLogs(serviceName, outputPath string) error {
 
 	outputPath = filepath.Join(outputPath, serviceName+"-internal")
 	serviceContainer := p.ContainerName(serviceName)
-	err = docker.Copy(serviceContainer, "/usr/share/elastic-agent/state/data/logs/default", outputPath)
+	err = docker.Copy(serviceContainer, "/usr/share/elastic-agent/state/data/logs/", outputPath)
```
Comment (jsoriano) [inline internal/stack/logs.go:61]: Dump before and after 8.5.0 seem to use different paths, are we ok with that? Or should we remove "default" from the path when present for consistency between versions?

**Review by jsoriano — APPROVED** [review]

File: internal/stack/logs.go (hunk 4 above)
Comment (mrodm) [reply internal/stack/logs.go:61]: Before 8.6.0 (where the Unified Agent log was introduced), logs were copied from the `default` folder. Since that version, that folder does not longer exist.

I thought updating the code to copy from the upper directory `logs` would be backwards compatible with versions <8.6.0.

```
 $ tree elastic-stack-dump-8.8.0-SNAPSHOT/logs/elastic-agent-internal/
elastic-stack-dump-8.8.0-SNAPSHOT/logs/elastic-agent-internal/
└── elastic-agent-20230505.ndjson

0 directories, 1 file

 $ tree elastic-stack-dump-8.5.0/logs/elastic-agent-internal/
elastic-stack-dump-8.5.0/logs/elastic-agent-internal/
├── default
│   ├── filebeat-20230505-1.ndjson
│   ├── filebeat-20230505-2.ndjson
│   ├── filebeat-20230505-3.ndjson
│   ├── filebeat-20230505.ndjson
│   ├── metricbeat-20230505-1.ndjson
│   └── metricbeat-20230505.ndjson
└── elastic-agent-20230505.ndjson

1 directory, 7 files
```

The difference for versions <8.6.0 is that it would copy one file more (in the example `/usr/share/elastic-agent/state/data/logs/elastic-agent-20230505.ndjson`)  instead of copying just the ones from the default folder.

Comment (mrodm) [reply internal/stack/logs.go:61]: Thanks for the clarification, understood :+1:

I would keep it as it is (adding that default folder). As you mention, those files in `default` folder will not be part of the logs for > 8.6.0 versions.
