### PR TITLE
Include positional arguments help for profile command

### LINKED ISSUE #1249: Improve help for command `elastic-package profile create`
The elastic-package command `elastic-package profile create` has no reference in the help to a required argument `profile-name`

Help output

```bash
➜ elastic-package profiles create --help
could not determine benchmark reports folder: locating build directory failed: can't create new build directory: package can be only built inside of a Git repository (.git folder is used as reference point)2023/05/04 13:45:21  WARN CommitHash is undefined, in both ~/.elastic-package/version and the compiled binary, config may be out of date.
Create a new profile

Usage:
  elastic-package profiles create [flags]

Flags:
      --from string   copy profile from the specified existing profile
  -h, --help          help for create

Global Flags:
  -v, --verbose   verbose mode
```

So when I try to run the command without that required parameter it fails with the following error without saying what is the name of the required argument or how to fix the error.

```bash
❯ elastic-package profiles create --from default -v
could not determine benchmark reports folder: locating build directory failed: can't create new build directory: package can be only built inside of a Git repository (.git folder is used as reference point)2023/05/04 13:24:51  WARN CommitHash is undefined, in both ~/.elastic-package/version and the compiled binary, config may be out of date.
2023/05/04 13:24:51 DEBUG Enable verbose logging
Error: create requires an argument
```

This is the version that I am using

```bash
➜ elastic-package version
could not determine benchmark reports folder: locating build directory failed: can't create new build directory: package can be only built inside of a Git repository (.git folder is used as reference point)2023/05/04 13:59:43  WARN CommitHash is undefined, in both ~/.elastic-package/version and the compiled binary, config may be out of date.
elastic-package v0.79.0 version-hash undefined (build time: unknown)
```

### PR DESCRIPTION
**Pull request by mrodm**
Fixes #1249 

This PR adds the required checks and documentation for positional arguments under `elastic-package profiles`  sub-commands.

Followed the same approach as in the example of the cobra documentation: https://umarcor.github.io/cobra/#positional-and-custom-arguments

Updated sub-commands:
- `elastic-package profiles create` allowed just 1 argument
- `elastic-package profiles delete` allowed just 1 argument
- `elastic-package profiles use` allowed just 1 argument
- `elastic-package profiles list` no args allowed

Example:
- New documentation:
```shell
 $ elastic-package profiles create -h
Create a new profile

Usage:
  elastic-package profiles create [profile] [flags]

Flags:
      --from string   copy profile from the specified existing profile
  -h, --help          help for create

Global Flags:
  -v, --verbose   verbose mode
```
- Add validation to ensure the required positional arguments are set:
```shell
 $ elastic-package profiles create
Error: accepts 1 arg(s), received 0
```

For `elastic-package profiles list` subcommand, this was not failing previously:
```shell
 $ elastic-package profiles list a
+-------------------+---------------------------+----------------+----------------+--------------------------------------------------------+
|       NAME        |       DATE CREATED        |      USER      |    VERSION     |                          PATH                          |
+-------------------+---------------------------+----------------+----------------+--------------------------------------------------------+
| default (current) | 2023-07-04T10:27:59+02:00 | mariorodriguez | f5a280a5-dirty | /home/mariorodriguez/.elastic-package/profiles/default |
+-------------------+---------------------------+----------------+----------------+--------------------------------------------------------+
| other             | 2023-07-25T11:17:46+02:00 | mariorodriguez | a564198e-dirty | /home/mariorodriguez/.elastic-package/profiles/other   |
+-------------------+---------------------------+----------------+----------------+--------------------------------------------------------+
```
Now, it reports an error if an unknown parameter is set:
```shell
 $ elastic-package profiles list a
Error: unknown command "a" for "elastic-package profiles list"
```

### CODE REVIEW

File: cmd/profiles.go [hunk 1]
```diff
@@ -75,12 +71,10 @@ User profiles can be configured with a "config.yml" file in the profile director
 	profileNewCommand.Flags().String(cobraext.ProfileFromFlagName, "", cobraext.ProfileFromFlagDescription)
 
 	profileDeleteCommand := &cobra.Command{
-		Use:   "delete",
+		Use:   "delete [profile]",
 		Short: "Delete a profile",
+		Args:  cobra.ExactArgs(1),
```
Comment (jsoriano) [inline cmd/profiles.go:76]: :+1: nice, probably we should review all subcommands to check if these options are needed in more places?

**Review by jsoriano — APPROVED** [review]

File: cmd/profiles.go (hunk 1 above)
Comment (mrodm) [reply cmd/profiles.go:76]: Yes, it looks like it would be good to add those validations in the other sub-commands.

Here it has been added for stack sub-commands too: https://github.com/elastic/elastic-package/pull/1412
