### PR TITLE
Ensure CAP_CHOWN capability is included if root user is required

### LINKED ISSUE #2330: Add CAP_CHOWN capability if package requires root privileges
By default, `elastic-package` drops all capabilities for the Elastic Agent container when running system tests. Just adds the capabilities added explicitly in the system test configuration file. 

Starting with 8.17.1-SNAPSHOT, packages that require root privileges cannot start the Elastic Agent container and they are failing with this error:
```
Error: the command is executed as root but the program files are not owned by the root user. execute the command as the user that owns the program files
```

To avoid this error with packages that require root privileges when starting the Elastic Agent container, it is required to add the `CAP_CHOWN` capability if it was not added by the package previously.

Example of packages failing using 8.18.0-SNAPSHOT:
- https://buildkite.com/elastic/integrations/builds/20201#019448b8-8404-4ea1-a8d6-3ec5ebd1244d

This root privileges could be defined as part of the manifest:
```yaml
agent:
  privileges:
    root: true
```

or in each system test configuration file (e.g. [example](https://github.com/elastic/integrations/blob/9f541bb9acff3cded8cc8bfec803c8595ba1969e/packages/apache_tomcat/data_stream/access/_dev/test/system/test-default-config.yml#L14-L15)):
```yaml
agent:
  user: root
```

### PR DESCRIPTION
**Pull request by mrodm**
Ensure that CAP_CHOWN capability is present in the docker-compose scenario for the Elastic Agent container when the package requires or sets root privileges.

Fixes #2330 

Additional:
- Take into account if a data stream manifest defines that it requires root privileges.
    - `system` package defines root privileges in the manifest of some of its data streams: [example data stream manifest link](https://github.com/elastic/integrations/blob/5468ed672708099ed7aabfbc95ccee36820dc091/packages/system/data_stream/auth/manifest.yml#L102-L104)

## Author's checklist
- [x] Test packages from integrations with 8.18.0-SNAPSHOT
    - https://buildkite.com/elastic/integrations/builds/20277
    - https://buildkite.com/elastic/integrations/builds/20287 (including root privileges defined in data stream manifests)
- [x] Test packages from integrations with their minimum Kibana version supported
    - https://buildkite.com/elastic/integrations/builds/20292

### CODE REVIEW

**Comment by mrodm** [comment]
Package `nginx` that does not require root:
```yaml
    healthcheck:
      test: "elastic-agent status"
      retries: 180
      interval: 1s

    cap_drop:
      - ALL
```

Package `auditd_manager` that require root:
```yaml
    healthcheck:
      test: "elastic-agent status"
      retries: 180
      interval: 1s
    
    pid: host

    user: root

    cap_add: [AUDIT_CONTROL,AUDIT_READ,CAP_CHOWN]
    
    cap_drop:
      - ALL
```

Package `fim` that requires root:
```yaml
    healthcheck:
      test: "elastic-agent status"
      retries: 180
      interval: 1s
  
    user: root
   
    cap_add: [CAP_CHOWN]
    
    cap_drop:
      - ALL
```

**Comment by mrodm** [comment]
test integrations

File: internal/testrunner/runners/system/tester.go [hunk 1]
```diff
@@ -456,11 +456,18 @@ func (r *tester) createAgentInfo(policy *kibana.Policy, config *testConfig, runI
 	info.Agent.AgentSettings = config.Agent.AgentSettings
 
 	// If user is defined in the configuration file, it has preference
-	// and it should not be overwritten by the value in the manifest
-	if info.Agent.User == "" && agentManifest.Privileges.Root {
+	// and it should not be overwritten by the value in the package or DataStream manifest
+	if info.Agent.User == "" && (r.pkgManifest.Agent.Privileges.Root || r.dataStreamManifest.Agent.Privileges.Root) {
```
Comment (mrodm) [inline internal/testrunner/runners/system/tester.go:460]: Previously, it was just considered the privileges settings from package manifest. It was no taken into account the one from the data stream manifest.

**Review by jsoriano — APPROVED** [review]
