### PR TITLE
Set terraform healthcheck after writing outputs

### LINKED ISSUE #1299: Terraform outputs in aws package make the test flaky
The terraform outputs in `aws` package as added [here](https://github.com/bhapas/elastic-package/commit/f8b3c8c6adbd730788d034f1665b925bc794627a#diff-56559e2b5a4a5f1a24f2de5a2bd7cf849068b89034b7bd05b13d42d75e30a19fR34) have flaky tests on CI.

The outputs are not generated sometimes and it results in the flaky test

Sample logs:
```
2023/06/08 11:43:57 DEBUG Unmarshalling terraform output json
2023/06/08 11:43:57 DEBUG **********JSON CONTENT**************** {
  "instance_id": {
    "sensitive": false,
    "type": "string",
    "value": "i-somerandomid"
  }
}
```

```
2023/06/08 12:22:06 DEBUG Unmarshalling terraform output json
2023/06/08 12:22:06 DEBUG **********JSON CONTENT****************
2023/06/08 12:22:06 DEBUG waiting for 1s before tearing down...
Error: error running package system tests: could not complete test run: could not setup service: could not handle terraform output error during json Unmarshal unexpected end of JSON input
+ cleanup
+ r=1
```

### PR DESCRIPTION
**Pull request by mrodm**
This PR updates the terraform shell script so the file used as a health check is written once the outputs have been saved to a file.

This will ensure that elastic-package would have available the JSON output contents when the container is considered healthy.

Closes #1299

### CODE REVIEW

File: internal/testrunner/runners/system/servicedeployer/_static/terraform_deployer_run.sh [hunk 1]
```diff
@@ -20,10 +20,12 @@ trap cleanup EXIT INT TERM
 
 terraform init
 terraform plan
-terraform apply -auto-approve && touch /tmp/tf-applied
+terraform apply -auto-approve
 
 terraform output -json > /output/tfOutputValues.json
 
+touch /tmp/tf-applied
```
Comment (bhapas) [inline internal/testrunner/runners/system/servicedeployer/_static/terraform_deployer_run.sh:27]: Should we document that this should be last statement in the script to avoid future issues?

```suggestion
touch /tmp/tf-applied # This is an indicator that the service is UP and so should be the last statement in the script
```

**Review by bhapas — COMMENTED** [review]
Mild nit. LGTM otherwise

**Review by bhapas — APPROVED** [review]

**Review by jsoriano — APPROVED** [review]
